name: Build and Deploy Calendar

on:
  # Trigger on push to main branch (optional)
  push:
    branches:
      - main

  # Trigger every 15 minutes
  schedule:
    - cron: '*/15 3-21 * * *'  # This runs every 15 minutes (but only from 3-21 UTC)

  # Allow manual trigger (optional)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Step 4: Run your Python script
      - name: Run the clean script
        run: python clean_ics.py

      # Step 5: Check git status and print changes (for debugging)
      - name: Check git status
        run: git status

      # Step 6: Check if the .ics file has changed and commit if necessary
      - name: Check if .ics file has changed
        run: |
          git diff --exit-code docs/cleaned_calendar.ics || echo "File has changed"

      # Step 7: Commit and push changes if the file has changed
      - name: Commit and push changes
        run: |
          git config user.name "1Kerbonaut"
          git config user.email "1Kerbonaut@users.noreply.github.com"
          git add docs/cleaned_calendar.ics
          git remote set-url origin https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/${{ github.repository }}          
          git commit -am "Update cleaned calendar"
          git push
          
          
          
          