name: Build and Deploy Calendar

on:
  # Trigger on push to main branch (optional)
  push:
    branches:
      - main

  # Trigger every 15 minutes
  schedule:
    - cron: '*/15 * * * *'  # This runs every 15 minutes

  # Allow manual trigger (optional)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # Step 4: Run your Python script
      - name: Run the clean script
        run: python clean_ics.py
